version: '3.8'

services:
  node-app:
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  fastapi:
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Only accessible locally
    environment:
      - ENVIRONMENT=production 