version: '3.8'

services:
  node-app:
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    command: sh -c "npm run start && tail -f /dev/null"

  fastapi:
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-service/app:/app/app:ro
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 